(function(){console.log("%c插件名：Canvas粒子背景\n\n依赖框架:jQuery V3.2.1\n\n封装日期：2019-05-18\n\n插件编号：1\n\n作者：Evangelion","color:red");var Cbg=function(options){var _this=this;_this.options=$.extend({control:"auto",autoCustom:true,autoCustomNum:10,container:"",type:"color",width:$(window).width(),height:$(window).height(),color:["#6525EE","#007AFF","orange","orangered"],imgUrl:"",size:[10,0.2,true],animation_type:{type:0,Israndom:false},interval_time:0,x:$(window).width()/2,y:$(window).height()/2,speed:10,IsboundaryControl:true},options)
if(_this.options.container==""||_this.options.container==" "){}else{var container=_this.options.container.substr(1);if(_this.options.container[0]=="."){c=$("."+container)[0];}else if(_this.options.container[0]=="#"){c=$("#"+container)[0];}
var c,ctx;c.width=_this.options.width;c.height=_this.options.height;ctx=c.getContext("2d");var dian_list=[];var dian=function(x,y){this.x=x;this.y=y;this.speed=_this.options.speed;if(_this.options.type==="color"){if(typeof _this.options.color==="string"){this.color=_this.options.color;}
if(_this.options.color.constructor===Array){this.color=_this.options.color[parseInt(Math.random()*_this.options.color.length)];}}
if(_this.options.type==="img"){this.img=new Image();if(typeof _this.options.imgUrl==="string"){this.img.src=_this.options.imgUrl;}
if(_this.options.imgUrl.constructor===Array){this.img.src=_this.options.imgUrl[parseInt(Math.random()*_this.options.imgUrl.length)];}}
if(_this.options.size[2]){this.size=Math.random()*(_this.options.size[0]-1)+1;}else{this.size=_this.options.size[0];}
if(_this.options.animation_type.Israndom){switch(_this.options.animation_type.type){case 0:this.dr_x=Math.cos(Math.random()*360);this.dr_y=Math.cos(Math.random()*360);break;case 1:this.dr_x=-(Math.random()*(1-0.1)+0.1);this.dr_y=Math.cos(Math.random()*360);break;case 2:this.dr_x=Math.random()*(1-0.1)+0.1;this.dr_y=Math.cos(Math.random()*360);break;case 3:this.dr_x=Math.cos(Math.random()*360);this.dr_y=Math.random()*(1-0.1)+0.1;break;case 4:this.dr_x=Math.cos(Math.random()*360);this.dr_y=-(Math.random()*(1-0.1)+0.1);break;case 5:this.dr_x=-(Math.random()*(1-0.1)+0.1);this.dr_y=-(Math.random()*(1-0.1)+0.1);break;case 6:this.dr_x=-(Math.random()*(1-0.1)+0.1);this.dr_y=Math.random()*(1-0.1)+0.1;break;case 7:this.dr_x=Math.random()*(1-0.1)+0.1;this.dr_y=-(Math.random()*(1-0.1)+0.1);break;case 8:this.dr_x=Math.random()*(1-0.1)+0.1;this.dr_y=Math.random()*(1-0.1)+0.1;break;default:break;}}
if(!_this.options.animation_type.Israndom){switch(_this.options.animation_type.type){case 0:this.dr_x=Math.cos(Math.random()*360);this.dr_y=Math.cos(Math.random()*360);break;case 1:this.dr_x=-(Math.random()*(1-0.1)+0.1);this.dr_y=0;break;case 2:this.dr_x=Math.random()*(1-0.1)+0.1;this.dr_y=0;break;case 3:this.dr_x=0;this.dr_y=Math.random()*(1-0.1)+0.1;break;case 4:this.dr_x=0;this.dr_y=-(Math.random()*(1-0.1)+0.1);break;case 5:this.dr_x=-(Math.random()*(1-0.1)+0.1);this.dr_y=this.dr_x;break;case 6:this.dr_x=-(Math.random()*(1-0.1)+0.1);this.dr_y=-this.dr_x;break;case 7:this.dr_x=Math.random()*(1-0.1)+0.1;this.dr_y=-this.dr_x;break;case 8:this.dr_x=Math.random()*(1-0.1)+0.1;this.dr_y=this.dr_x;break;default:break;}}
dian_list.push(this);}
dian.prototype.render=function(){this.x+=this.dr_x*this.speed;this.y+=this.dr_y*this.speed;this.size-=_this.options.size[1];if(_this.options.IsboundaryControl){this.boundaryControl();}
if(this.size<=0){this.godie();}else{ctx.beginPath();if(_this.options.type==="color"){ctx.fillStyle=this.color;ctx.arc(this.x,this.y,this.size,0,2*Math.PI);ctx.fill();}
if(_this.options.type==="img"){ctx.drawImage(this.img,this.x,this.y,this.size,this.size);}}}
dian.prototype.godie=function(){for(var j=0;j<dian_list.length;j++){if(this===dian_list[j]){dian_list.splice(j,1);}}}
dian.prototype.boundaryControl=function(){if((this.x+(this.size))>=c.width||(this.x-this.size)<=0){this.dr_x*=-1;}
if((this.y+(this.size))>=c.height||(this.y-this.size)<=0){this.dr_y*=-1;}}
if(_this.options.control=="mouse"){$(document).mousemove(function(event){new dian(event.clientX,event.clientY);})}
if(_this.options.control=="auto"){var w_max=c.width-_this.options.size[0];var h_max=c.height-_this.options.size[0];if(_this.options.autoCustom){for(var a=0;a<_this.options.autoCustomNum;a++){var x=Math.random()*(w_max-_this.options.size[0])+_this.options.size[0];var y=Math.random()*(h_max-_this.options.size[0])+_this.options.size[0];new dian(x,y);}}else{setInterval(function(){var x=Math.random()*(w_max-_this.options.size[0])+_this.options.size[0];var y=Math.random()*(h_max-_this.options.size[0])+_this.options.size[0];new dian(x,y);},_this.options.interval_time)}}
if(_this.options.control=="coordinate"){setInterval(function(){var x=_this.options.x;var y=_this.options.y;new dian(x,y);},_this.options.interval_time)}
var draw=function(){ctx.clearRect(0,0,c.width,c.height);var length=length=dian_list.length
for(var i=0;i<length;i++){var item=dian_list[i];item&&item.render()}
window.requestAnimationFrame(draw);}
window.requestAnimationFrame(draw);}};window.Cbg=Cbg;}())